### ISSUE TITLE
Can't get to minecraft client

### ISSUE THREAD

**Issue by rsalek** [argymeg/MetaboCraft#1]
Hello Anargyros,

Nice work, I tried your docker implementation and the part for uploading data works but could not get to Minecraft client?  

I followed 
> Take note of the port mapped to 25565 - this is the host and port that needs to be put into the minecraft client. Also take note of the port mapped to 32909 - this is the url that needs to be entered to upload data.

Tried various ports but no luck, any suggestion?

**Comment by RonanDaly** [comment]
I don't quite follow -- when you opened your minecraft client (version 1.11.2), did you do log in, select Multiplayer, then Add server, select a name for the server and enter its address given? If you're using Kitematic, it's the one under Access URL, corresponding to the port 25565.

**Comment by rsalek** [comment]
My problem seems that I can't open minecraft client when clicking on the local port corresponding to the port 25565, nothing happens (localhost refused to connect or localhost didn’t send any data.
ERR_EMPTY_RESPONSE).  I use Kitematic on mac, version Version 17.09.0-ce-mac35 (19611)

MetaboCraft file uploader work, though

**Comment by RonanDaly** [comment]
Are you putting the host and port into your web browser? You need to open your minecraft client first and then enter the information there using the above procedure.

**Comment by RonanDaly** [comment]
Wait a sec, do you have Minecraft installed on your computer? You need version 1.11.2 already installed.

**Comment by rsalek** [comment]
he he, I assumed it is in the container!

**Comment by RonanDaly** [comment]
Unfortunately, we couldn't redistribute that!

**Comment by rsalek** [comment]
ok, I have now the client installed, with ver 1.11.2. Does it have to be a paid account to do multiplayer?  I assume sever version is in the 'docker' or should I installed it as well? https://minecraft.net/en-us/download/server
I think I need help with Minecraft setup! :)

**Comment by RonanDaly** [comment]
I believe it does have to be a paid account -- when you start up the client, you need to log on with your minecraft user name. The server is completely self contained in the docker container -- it's built upon an open source server.

**Comment by rsalek** [comment]
Alright, thank you, Ronan.
